# Generated by Django 4.2 on 2023-05-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
