# Generated by Django 4.1.7 on 2023-03-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=12)),
                ('user_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('terms_condition', models.BooleanField(default=False)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('registered_datetime', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=12)),
                ('user_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('terms_condition', models.BooleanField(default=False)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('user_created', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),

            ],
        ),
        migrations.CreateModel(
            name='HouseShiftingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shifting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=500, null=True)),
                ('moving_datetime', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=500, null=True)),
                ('pickup_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_lift', models.CharField(blank=True, max_length=50, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=500, null=True)),
                ('drop_address', models.CharField(blank=True, max_length=500, null=True)),
                ('drop_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('drop_lift', models.CharField(blank=True, max_length=50, null=True)),
                ('order_placed_datetime', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),

            ],
        ),
    ]
