# Generated by Django 4.2 on 2023-05-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0002_register_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_shifting_details_id', models.CharField(blank=True, max_length=100, null=True)),
                ('house_shifting_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_shifting_details_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ware_house_storing_details_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ware_house_storing_products_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shifting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
