# Generated by Django 4.2 on 2023-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0003_orderbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
