# Generated by Django 4.1.7 on 2023-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0003_warehousestoragedetails_register_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenshiftingvehicle',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chosenshiftingvehicle',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseselectedvehicle',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseselectedvehicle',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
