# Generated by Django 4.2 on 2023-05-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0004_orderbooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouseselectedvehicle',
            name='vehicle_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HouseShiftingSelectedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_image', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('house_shifting_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_app.houseshiftingdetails')),
            ],
        ),
    ]
