# Generated by Django 4.2 on 2023-05-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0006_alter_houseshiftingselectedvehicle_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseshiftingdetails',
            name='house_shifting_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='chosen_shifting_vehicle_details_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
