# Generated by Django 4.2 on 2023-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0007_houseshiftingdetails_house_shifting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenshiftingvehicle',
            name='order_place_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
