# Generated by Django 4.2 on 2023-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0008_chosenshiftingvehicle_order_place_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenshiftingvehicle',
            name='vehicle_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chosenshiftingvehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chosenshiftingvehicle',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
