# Generated by Django 4.2 on 2023-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0009_chosenshiftingvehicle_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='booking_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
