# Generated by Django 4.2 on 2023-06-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0010_orderbooking_booking_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseshiftingselectedvehicle',
            name='total_shifting_KMs',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
        migrations.AddField(
            model_name='houseshiftingselectedvehicle',
            name='vehicle_amount',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
