# Generated by Django 4.2 on 2023-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0011_houseshiftingselectedvehicle_total_shifting_kms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenshiftingvehicle',
            name='vehicle_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houseshiftingproducts',
            name='product_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousestoringproducts',
            name='product_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
